spring:
  application:
    name: ec-site-playground

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/ec_site_playground
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true